print ("Hi Mit Where is the key")
print("it's their on key holder")
print("Can you see ? ")
print("Yes")
Keys=('key + design')
Key   = print ("0````````")
design=  print (      "   ||||||")
print('keys')
